config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'SysUser', at: '/auth'
    end
    namespace :salesman do
      mount_devise_token_auth_for 'Salesman', at: '/auth'
    end
    namespace :user do
      mount_devise_token_auth_for 'User', at: '/auth'
    end
  end
  mount ActionCable.server, at: '/cable'
  mount API::Base => '/api'

  get 'fb_comment_path', to: 'application#fb_comment_path'
  root 'users/base#root'

  post 'search_product', to: 'application#search_product'
  post 'search_fb_answer', to: 'application#search_fb_answer'
  patch 'get_product_features', to: 'application#get_product_features'

  devise_for :admin_users, path: :admin, controllers: {
      sessions: 'admin_users/sessions',
      registrations: 'admin_users/registrations',
      passwords: 'admin_users/passwords'
  }

  devise_scope :admin_user do
    get 'admin/passwords/edit_password', to: 'admin_users/registrations#edit_password'
    patch 'admin/passwords', to: 'admin_users/registrations#update_password'
  end

  devise_for :users, path: :user, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords',
  }

  devise_scope :user do
    get 'user/passwords/edit_password', to: 'users/registrations#edit_password'
    patch 'user/passwords', to: 'users/registrations#update_password'
  end

  devise_for :operators, path: :operator, controllers: {
      registrations: 'operators/registrations',
      sessions: 'operators/sessions',
      passwords: 'operators/passwords',
  }

  devise_scope :operator do
    get 'operator/passwords/edit_password', to: 'operators/registrations#edit_password'
    patch 'operator/passwords', to: 'operators/registrations#update_password'
  end

  devise_for :logistics, path: :logistic, controllers: {
      registrations: 'logistics/registrations',
      sessions: 'logistics/sessions',
      passwords: 'logistics/passwords',
  }

  devise_scope :logistic do
    get 'logistic/passwords/edit_password', to: 'logistics/registrations#edit_password'
    patch 'logistic/passwords', to: 'logistics/registrations#update_password'
  end


  namespace :admin_users, path: :admin do
    root 'users#index'
    resources :administrators, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :users, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :logistics, only: [:index, :create, :new, :show, :edit, :update, :destroy]

    namespace :bank_logins do
      get 'login'
    end

    namespace :facebooks do
      get 'posts'
      get 'attachments'
      get 'to_archives'
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :users, path: :user do
    root "base#root"
    get "panel", to: 'pages#panel'
    post 'uploads' => 'uploads#create'

    namespace :calc do
      get 'vrptw'
    end

    resources :product_categories, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :customers, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :customer_warehouses, only: [:create, :new, :edit, :update, :destroy]
    resources :customer_imports, only: [:new, :create] do
      collection do
        post 'customer_warehouse'
      end
    end
    resources :product_feature_groups, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :product_features, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :product_feature_options, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :category_filter_groups, only: [:index, :create, :new, :show, :edit, :update, :destroy], path: "category/filters"
    resources :product_discounts, only: [:create, :new, :edit, :update, :destroy]
    resources :product_feature_items, only: [:create, :new, :destroy] do
      collection do
        get 'balance'
        post 'get_feature_items'
        get 'set_balance'
        post 'load_features'
        post 'itoms'
        patch 'update_feature'
      end
    end
    resources :products, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        patch 'get_product_category_children'
        patch 'form_price'
        patch 'form_information'
        patch 'form_image_video'
        patch 'form_package'
        post 'technical_spec_items'
      end
    end
    resources :product_supply_orders, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
      collection do
        patch 'form_feature'
        post 'last_product_price'
        get 'to_product'
        get 'to_excel'
      end
    end
    resources :product_locations, only: [:index, :create, :new, :edit, :update, :destroy]

    get 'product_incomes/shipping_show/:id', to: 'product_incomes#shipping_show'
    resources :product_incomes do
      collection do
        patch 'get_location_children'
        patch 'get_supply_order_info'
        patch 'insert_shipping_ub'
        patch 'insert_half_ub'
        get 'locations'
        patch 'set_location'
        post 'search_products'
        post 'search_half_products'
        post 'search_supply_feature'
        post 'insert_sample_product'
        post 'income_logs'
        patch 'update_income_log'
      end
    end
    resources :operators, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :salesmen, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :ali_categories, only: [:index, :create, :show, :edit, :update, :destroy] do
      collection do
        patch 'set_prod'
        patch 'set_name_as_filter'
        get 'form_filter'
        patch 'update_filter'
      end
    end

    resources :bank_accounts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :bank_dealing_accounts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :brands, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :manufacturers, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :technical_specifications, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :size_instructions, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :fb_posts do
      collection do
        post 'download'
      end
    end
    resources :fb_comments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        patch 'hide'
      end
    end
    resources :fb_comment_archives, only: [:index, :show] do
      collection do
        get 'report'
        post 'get_message_url'
      end
    end
    resources :bank_transactions
    resources :store_transfers do
      collection do
        patch 'get_product_features'
        post 'get_product_balance'
      end
    end
    resources :direct_sales do
      collection do
        post 'get_product_balance'
      end
    end
    resources :sms_messages, only: [:index, :create, :new]
    namespace :delivery_reports do
      get 'index'
      get 'salary'
    end
    resources :sale_taxes, only: [:index, :create, :new, :edit, :update]
    resources :product_sales, only: [:index] do
      collection do
        post 'check_register'
        post 'tax'
        get 'report'
      end
    end

    namespace :product_reports do
      get 'track'
      get 'track_logs'
      post 'track_log'
    end

    namespace :supply_calculations do
      get 'supply_orders'
      get 'income_products'
      patch 'set_calculated'
      patch 'set_all_calculated'
      get 'for_invoice'
      get 'purchased_er'
      get 'received_er'
      get 'ship_ub'
      get 'calculate'
    end

    namespace :warehouse_reports do
      get 'daily'
      get 'products'
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :operators, path: :operator do
    root "base#root"

    resources :product_sales, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        post 'search_locations'
        post 'edit_location'
        post 'update_location'
        post 'search_khoroos'
        post 'get_last_location'
        post 'get_product_balance'
        patch 'update_status'
        post 'get_bonus'
        post 'next_status'
        post 'get_radius_sales'
      end
    end

    resources :fb_comments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        patch 'like'
        patch 'hide'
      end
    end
    resources :fb_comment_actions
    resources :fb_comment_archives, only: [:index, :show] do
      collection do
        get 'report'
        post 'get_message_url'
      end
    end

    resources :product_sale_calls, only: [:index, :new, :edit, :update, :show] do
      collection do
        post 'auto_save'
        post 'get_prev_sales'
        post 'check_sale_order'
      end
    end

    resources :bank_transactions, only: [:index]
    resources :sms_messages, only: [:index, :create, :new]
    resources :loc_districts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :bonus, only: [:index, :edit, :update, :destroy]
    resources :loc_khoroos, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :locations, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        post 'get_location'
      end
    end
    resources :location_zones
    namespace :distributing do
      get 'index'
      post 'set_travel'
      post 'travel_routes'
      post 'product_sales'
      post 'add_product_sale'
      post 'change_route_queue'
      patch 'remove_route'
      post 'distributing'
      post 'salesman_track'
    end

    resources :salesman_travels do
      collection do
        get 'zone'
        get 'map'
        post 'insert_sale'
        post 'insert_to_sale'
      end
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :logistics, path: :logistic do
    root "base#root"

app/controllers/admin_users/users_controller.rb
class AdminUsers::UsersController < AdminUsers::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @semail = params[:email]
    @sname = params[:name]
    @sphone = params[:phone]
    @users = User.search(@sname, @semail, @sphone).page(params[:page])
    cookies[:user_page_number] = params[:page]
  end

  def new
    @user = User.new
    @user.user_permission_rels << UserPermissionRel.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.send_first_password_instructions
      flash[:success] = t('alert.saved_successfully')
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @user.attributes = user_params
    if @user.save
      flash[:success] = t('alert.info_updated')
      redirect_to :action => 'show', id: @user.id
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy!
    flash[:success] = t('alert.deleted_successfully')
    redirect_to action: :index
  end

  # def user_sign_in
  #   sign_in :user, @user
  #   redirect_to users_root_path
  # end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:surname, :name, :gender, :email, :phone, :user_position_id,
                                 user_permission_rels_attributes: [:id, :user_permission_id, :role, :_destroy])
  end
end

app/controllers/api/user/base.rb
module API
  module USER
    class Base < Grape::API
      version 'user', using: :path
      format :json
      formatter :json, Grape::Formatter::Jbuilder

      # 例外ハンドル
      rescue_from ActiveRecord::RecordNotFound do |e|
        error!("Couldn't find data", 404)
      end

      rescue_from ActiveRecord::RecordNotUnique do |e|
        error!(e.message, 422)
      end

      rescue_from ActiveRecord::RecordInvalid do |e|
        error!(e.message, 422)
      end

      helpers do
        def authenticate_error!
          h = {'Access-Control-Allow-Origin' => "*",
               'Access-Control-Request-Method' => %w{GET POST OPTIONS}.join(",")}
          error!('You need to log in to use the app.', 401, h)
        end

        def current_user
          @resource
        end

        # header から認証に必要な情報を取得
        def authenticate_user!
          return if @resource
          uid = request.headers['Uid']
          token = request.headers['Access-Token']
          client = request.headers['Client']
          user = User.find_by(uid: uid)
          if user && user.valid_token?(token, client)
            @resource = user
          else
            @resource = nil
            authenticate_error!
          end
        end
      end

      mount API::USER::Passwords

      before do
        authenticate_user!
      end

      # mounts
      mount API::USER::Travels
      mount API::USER::Sales
      mount API::USER::Users
      mount API::USER::Locations
    end
  end
end

app/controllers/api/user/entities.rb
module API
  module USER
    module Entities

      class User < Grape::Entity
        expose :name, :uid, :email, :phone
      end

      class Salesman < Grape::Entity
        expose :id, :id_number, :surname, :name, :avatar, :avatar_tumb
      end

      class SalesmanTravels < Grape::Entity
        expose :id, :id_number, :load_at, :delivery_at, :sign_at, :load_at, :load_count, :load_sum
        expose :salesman, using: API::USER::Entities::Salesman
      end

      class ProductFeatureItem < Grape::Entity
        expose :id, :barcode, :product_id, :product_name, :name, :image_url, :quantity
      end

      class ProductWarehouse < Grape::Entity
        expose :id, :barcode, :name, :code, :desk, :feature, :image, :quantity, :load_at, :add_stock
      end

      class Products < Grape::Entity
        expose :id, :code, :name
      end

      class ProductFeatures < Grape::Entity
        expose :id, :name, :balance, :price
      end

      class SalesmanTravelRoutes < Grape::Entity
        expose :id, :queue, :loc_name, :phone, :product_count, :product_sale_id
      end

      class Notification < Grape::Entity
        expose :created_at, :title, :body_u, :avatar_s, :salesman_travel_id, :return_sign_id
      end

      class SalesmanReturnSign < Grape::Entity
        expose :id, :salesman_name, :products
      end

      class SalesmanReturn < Grape::Entity
        expose :id, :quantity, :product_code, :product_name, :product_image, :product_feature, :product_barcode
      end

      class ProductFeatureItemList < Grape::Entity
        expose :id, :barcode, :product_name, :name, :thumb_url, :image_url
      end

      class LocationTransferItem < Grape::Entity
        expose :id, :quantity, :transferred, :desk
        expose :product_feature_item, using: API::USER::Entities::ProductFeatureItemList
      end

      class LocationTransfer < Grape::Entity
        expose :id, :location_name
        expose :product_location_trans_items, using: API::USER::Entities::LocationTransferItem
      end

      class LocationTransferList < Grape::Entity
        expose :id, :location_name, :quantity, :transferred
      end

      class ProductLocation < Grape::Entity
        expose :name, :quantity
      end

      class TransferHistoryBySalesman < Grape::Entity
        expose :salesman_id, :salesman_name, :quantity
      end

      class ProductWarehouseUserSign < Grape::Entity
        expose :barcode, :name, :code, :desk, :feature, :image, :quantity, :load_at, :user_sign
      end

      class SalesmanReturnUserSign < Grape::Entity
        expose :barcode, :name, :code, :desk, :feature, :image, :quantity, :created_at, :user_sign
      end
      class LogStatus < Grape::Entity
        expose :id, :name
      end
    end
  end
end

app/controllers/api/user/users.rb
module API
  module USER
    class Users < Grape::API
      resource :users do

        get do
          present :user, current_user, with: API::USER::Entities::User
        end
        resource :device do
          desc "PATCH users/device"
          params do
            requires :device_token, type: String
          end
          patch do
            user = current_user
            user.update_attribute(:device_token, params[:device_token])

            present :updated_at, user.updated_at
          end
        end

        resource :notifications do
          desc "GET users/notifications"
          get do
            notifications = Notification.by_user(current_user.id).page(1)
            present :notifications, notifications, with: API::USER::Entities::Notification
          end
        end

        resource :notification do
          desc "POST users/notification"
          params do
            requires :title, type: String
            requires :content, type: String
            optional :token, type: String
          end
          patch do
            user = current_user
            if params[:token].present?
              user.device_token = params[:token]
            end
            ApplicationController.helpers.send_notification(user,
                                                            user.push_options('user', params[:title], params[:content]))
            present :updated_at, Time.now
          end
        end

        resource :change do
          resource :pin do
            desc "PATCH users/change/pin"
            params do
              requires :pin_code, type: String
            end
            patch do
              user = current_user
              user.pin_code = params[:pin_code]

              if user.save
                present :updated_at, user.updated_at
              else
                error!(user.errors.full_messages, 422)
              end
            end
          end
        end

      end
    end
  end
end

app/views/users/operators/_form.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1><%= t('activerecord.models.operator') + t(@operator.persisted? ? 'titles.edit' : 'titles.add') %></h1>
  </section>
  <section class="content">
    <div class="box box-info">
      <%= form_with model: @operator, url: @operator.persisted? ? users_operator_path : users_operators_path, method: @operator.persisted? ? :patch : :post, local: true, :html => {class: 'form-horizontal'} do |f| %>
        <%= form_body do %>
          <div class="form-group">
            <%= f.label :surname, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@operator, :surname) %>">
              <%= field_errors(@operator, :surname) %>
              <%= f.text_field :surname, class: 'form-control', placeholder: t('activerecord.attributes.operator.surname') %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :name, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@operator, :name) %>">
              <%= field_errors(@operator, :name) %>
              <%= f.text_field :name, class: 'form-control', placeholder: t('activerecord.attributes.operator.name') %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :gender, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 radio-group p-t-5 <%= get_error_class(@operator, :gender) %>">
              <%= field_errors(@operator, :gender) %>
              <%= f.collection_radio_buttons :gender, Operator.genders_i18n, :first, :second do |b| %>
                <%= b.radio_button %>&nbsp;&nbsp;<%= b.text %> &nbsp;&nbsp;
              <% end %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@operator, :email) %>">
              <%= get_user_field_errors(@operator, :email) %>
              <%= f.email_field :email, class: 'form-control', placeholder: t('activerecord.attributes.operator.email'), disabled: @operator.persisted? %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :phone, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@operator, :phone) %>">
              <%= field_errors(@operator, :phone) %>
              <%= f.text_field :phone, class: 'form-control', placeholder: t('activerecord.attributes.operator.phone') %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :order_sys_name, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@operator, :order_sys_name) %>">
              <%= field_errors(@operator, :order_sys_name) %>
              <%= f.text_field :order_sys_name, class: 'form-control', placeholder: t('activerecord.attributes.operator.order_sys_name') %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :operator_permission_rels, class: 'col-sm-3 control-label' %>

            <div class="col-sm-9 cocoon-nested-form">
              <div class="<%= get_error_class(@operator, :operator_permission_rels) %>">
                <%= field_errors(@operator, :operator_permission_rels) %>
                <table class="table table-bordered" id="tb_operator_permission_rels">
                  <tr>
                    <th width="45%"><%= t('activerecord.attributes.operator_permission_rel.operator_permission_id') %></th>
                    <th width="45%"><%= t('activerecord.attributes.operator_permission_rel.role') %></th>
                    <th width="50px"></th>
                  </tr>
                  <%= f.fields_for :operator_permission_rels do |rel| %>
                    <%= render 'operator_permission_rel_fields', f: rel %>
                  <% end %>
                </table>
              </div>
              <div class="links item_append">
                <%= link_to_add_association f, :operator_permission_rels, data: {association_insertion_node: '#tb_operator_permission_rels', association_insertion_method: :append} do %>
                  <%= nested_add_btn %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="action-buttons">
            <%= f.submit t('controls.button.save'), class: 'btn btn-warning' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>
</div>

app/views/users/operators/_operator_permission_rel_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= field_errors f.object, :operator_permission_id %>
    <%= f.collection_select :operator_permission_id, OperatorPermission.by_queue, :id, :description,
                            {:prompt => t('controls.select.none')}, {class: 'form-control selectpicker'} %>
  </td>
  <td>
    <%= field_errors f.object, :role %>
    <%= f.select :role, OperatorPermissionRel.roles.keys.map {|k| [OperatorPermissionRel.roles_i18n[k], k]}, {:prompt => t('controls.select.none')}, {class: 'form-control selectpicker'} %>
  </td>
  <td class="va-mid remove">
    <%= link_to_remove_association f, data: {confirm: t('are_you_sure')} do %>
      <%= nested_remove_btn %>
    <% end %>
  </td>
</tr>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker('refresh');
    })
</script>

app/views/users/operators/index.html.erb
<div class="content-wrapper">
  <div class="col-md-12 m-t-10 m-b-10">
    <div class="row">
      <%= form_with url: users_operators_path, method: "get", class: 'form-horizontal', local: true do |f| %>
        <div class="col-md-3 search">
          <%= text_field_tag :name, @sname, {class: 'form-control search', placeholder: t('filters.name')} %>
        </div>
        <div class="col-md-3 search">
          <%= text_field_tag :email, @semail, {class: 'form-control search', placeholder: t('filters.email')} %>
        </div>
        <div class="col-md-3 search">
          <%= text_field_tag :phone, @sphone, {class: 'form-control search', placeholder: t('filters.phone')} %>
        </div>
        <div class="col-md-3 search">
          <%= submit_tag t('controls.button.searching') + " (" + @operators.total_count.to_s + ")", :class => 'btn blck-btn pull-left' %>

          <% is_manage = can? :manage, Operator %>
          <% if is_manage %>
            <%= link_to t('controls.button.create'), new_users_operator_path, class: 'btn btn-warning pull-right' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <section class="content container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <%= render 'layouts/flash_message' %>

          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <tr>
                <th class="th-center va-mid"><%= t('activerecord.attributes.operator.name') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.operator.email') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.operator.phone') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.operator.order_sys_name') %></th>
              </tr>
              <% @operators.each do |operator| %>
                <tr>
                  <td class="va-mid underline"><%= link_to operator.name, users_operator_path(operator) %></td>
                  <td class="va-mid"><%= operator.email %></td>
                  <td class="td-center va-mid"><%= operator.phone %></td>
                  <td class="va-mid"><%= operator.order_sys_name %></td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
        <%= paginate @operators %>
      </div>
    </div>
  </section>
</div>

app/views/users/operators/show.html.erb
<div class="content-wrapper">
  <%= render 'layouts/flash_message' %>

  <section class="content-header align-left padding-15">
    <h1> <%= t('titles.operator_show') %> </h1>
  </section>

  <div class="action-buttons">
    <% if can? :manage, Operator %>
      <%= link_to t('controls.button.edit'), edit_users_operator_path(@operator), class: 'btn btn-info' %>
      <%= link_to t('controls.button.delete'), users_operator_path(@operator), method: :delete, data: {confirm: t('are_you_sure')}, class: 'btn btn-danger' %>
    <% end %>
    <%= link_to t('titles.back_to_list'), users_operators_path(page: cookies[:operator_page_number]), {class: "btn blck-btn"} %>
  </div>
  <%= show_body do %>
    <div class="box">
      <div class="box-body table-responsive no-padding">
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.operator.surname') %> :</div>
          <div class="col-data"><%= @operator.surname %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.operator.name') %> :</div>
          <div class="col-data"><%= @operator.name %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.operator.gender') %> :</div>
          <div class="col-data"><%= @operator.gender_i18n %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.operator.email') %> :</div>
          <div class="col-data"><%= @operator.email %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.operator.phone') %> :</div>
          <div class="col-data"><%= @operator.phone.presence || :'---' %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.operator.operator_permission_rels') %> :</div>
          <div class="col-data">
            <table class="table table-bordered">
              <thead>
              <tr>
                <th><%= t('activerecord.attributes.operator_permission_rel.operator_permission_id') %></th>
                <th><%= t('activerecord.attributes.operator_permission_rel.role') %></th>
              </tr>
              </thead>
              <tbody>
              <% @operator.operator_permission_rels.each do |r| %>
                <tr>
                  <td class="va-mid"><%= r.operator_permission.description %></td>
                  <td class="va-mid"><%= r.role_i18n %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>