config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'SysUser', at: '/auth'
    end
    namespace :salesman do
      mount_devise_token_auth_for 'Salesman', at: '/auth'
    end
    namespace :user do
      mount_devise_token_auth_for 'User', at: '/auth'
    end
  end
  mount ActionCable.server, at: '/cable'
  mount API::Base => '/api'

  get 'fb_comment_path', to: 'application#fb_comment_path'
  root 'users/base#root'

  post 'search_product', to: 'application#search_product'
  post 'search_fb_answer', to: 'application#search_fb_answer'
  patch 'get_product_features', to: 'application#get_product_features'

  devise_for :admin_users, path: :admin, controllers: {
      sessions: 'admin_users/sessions',
      registrations: 'admin_users/registrations',
      passwords: 'admin_users/passwords'
  }

  devise_scope :admin_user do
    get 'admin/passwords/edit_password', to: 'admin_users/registrations#edit_password'
    patch 'admin/passwords', to: 'admin_users/registrations#update_password'
  end

  devise_for :users, path: :user, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords',
  }

  devise_scope :user do
    get 'user/passwords/edit_password', to: 'users/registrations#edit_password'
    patch 'user/passwords', to: 'users/registrations#update_password'
  end

  devise_for :operators, path: :operator, controllers: {
      registrations: 'operators/registrations',
      sessions: 'operators/sessions',
      passwords: 'operators/passwords',
  }

  devise_scope :operator do
    get 'operator/passwords/edit_password', to: 'operators/registrations#edit_password'
    patch 'operator/passwords', to: 'operators/registrations#update_password'
  end

  devise_for :logistics, path: :logistic, controllers: {
      registrations: 'logistics/registrations',
      sessions: 'logistics/sessions',
      passwords: 'logistics/passwords',
  }

  devise_scope :logistic do
    get 'logistic/passwords/edit_password', to: 'logistics/registrations#edit_password'
    patch 'logistic/passwords', to: 'logistics/registrations#update_password'
  end


  namespace :admin_users, path: :admin do
    root 'users#index'
    resources :administrators, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :users, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :logistics, only: [:index, :create, :new, :show, :edit, :update, :destroy]

    namespace :bank_logins do
      get 'login'
    end

    namespace :facebooks do
      get 'posts'
      get 'attachments'
      get 'to_archives'
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :users, path: :user do
    root "base#root"
    get "panel", to: 'pages#panel'
    post 'uploads' => 'uploads#create'

    namespace :calc do
      get 'vrptw'
    end

    resources :product_categories, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :customers, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :customer_warehouses, only: [:create, :new, :edit, :update, :destroy]
    resources :customer_imports, only: [:new, :create] do
      collection do
        post 'customer_warehouse'
      end
    end
    resources :product_feature_groups, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :product_features, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :product_feature_options, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :category_filter_groups, only: [:index, :create, :new, :show, :edit, :update, :destroy], path: "category/filters"
    resources :product_discounts, only: [:create, :new, :edit, :update, :destroy]
    resources :product_feature_items, only: [:create, :new, :destroy] do
      collection do
        get 'balance'
        post 'get_feature_items'
        get 'set_balance'
        post 'load_features'
        post 'itoms'
        patch 'update_feature'
      end
    end
    resources :products, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        patch 'get_product_category_children'
        patch 'form_price'
        patch 'form_information'
        patch 'form_image_video'
        patch 'form_package'
        post 'technical_spec_items'
      end
    end
    resources :product_supply_orders, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
      collection do
        patch 'form_feature'
        post 'last_product_price'
        get 'to_product'
        get 'to_excel'
      end
    end
    resources :product_locations, only: [:index, :create, :new, :edit, :update, :destroy]

    get 'product_incomes/shipping_show/:id', to: 'product_incomes#shipping_show'
    resources :product_incomes do
      collection do
        patch 'get_location_children'
        patch 'get_supply_order_info'
        patch 'insert_shipping_ub'
        patch 'insert_half_ub'
        get 'locations'
        patch 'set_location'
        post 'search_products'
        post 'search_half_products'
        post 'search_supply_feature'
        post 'insert_sample_product'
        post 'income_logs'
        patch 'update_income_log'
      end
    end
    resources :operators, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :salesmen, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :ali_categories, only: [:index, :create, :show, :edit, :update, :destroy] do
      collection do
        patch 'set_prod'
        patch 'set_name_as_filter'
        get 'form_filter'
        patch 'update_filter'
      end
    end

    resources :bank_accounts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :bank_dealing_accounts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :brands, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :manufacturers, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :technical_specifications, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :size_instructions, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :fb_posts do
      collection do
        post 'download'
      end
    end
    resources :fb_comments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        patch 'hide'
      end
    end
    resources :fb_comment_archives, only: [:index, :show] do
      collection do
        get 'report'
        post 'get_message_url'
      end
    end
    resources :bank_transactions
    resources :store_transfers do
      collection do
        patch 'get_product_features'
        post 'get_product_balance'
      end
    end
    resources :direct_sales do
      collection do
        post 'get_product_balance'
      end
    end
    resources :sms_messages, only: [:index, :create, :new]
    namespace :delivery_reports do
      get 'index'
      get 'salary'
    end
    resources :sale_taxes, only: [:index, :create, :new, :edit, :update]
    resources :product_sales, only: [:index] do
      collection do
        post 'check_register'
        post 'tax'
        get 'report'
      end
    end

    namespace :product_reports do
      get 'track'
      get 'track_logs'
      post 'track_log'
    end

    namespace :supply_calculations do
      get 'supply_orders'
      get 'income_products'
      patch 'set_calculated'
      patch 'set_all_calculated'
      get 'for_invoice'
      get 'purchased_er'
      get 'received_er'
      get 'ship_ub'
      get 'calculate'
    end

    namespace :warehouse_reports do
      get 'daily'
      get 'products'
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :operators, path: :operator do
    root "base#root"

    resources :product_sales, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        post 'search_locations'
        post 'edit_location'
        post 'update_location'
        post 'search_khoroos'
        post 'get_last_location'
        post 'get_product_balance'
        patch 'update_status'
        post 'get_bonus'
        post 'next_status'
        post 'get_radius_sales'
      end
    end

    resources :fb_comments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        patch 'like'
        patch 'hide'
      end
    end
    resources :fb_comment_actions
    resources :fb_comment_archives, only: [:index, :show] do
      collection do
        get 'report'
        post 'get_message_url'
      end
    end

    resources :product_sale_calls, only: [:index, :new, :edit, :update, :show] do
      collection do
        post 'auto_save'
        post 'get_prev_sales'
        post 'check_sale_order'
      end
    end

    resources :bank_transactions, only: [:index]
    resources :sms_messages, only: [:index, :create, :new]
    resources :loc_districts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :bonus, only: [:index, :edit, :update, :destroy]
    resources :loc_khoroos, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :locations, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        post 'get_location'
      end
    end
    resources :location_zones
    namespace :distributing do
      get 'index'
      post 'set_travel'
      post 'travel_routes'
      post 'product_sales'
      post 'add_product_sale'
      post 'change_route_queue'
      patch 'remove_route'
      post 'distributing'
      post 'salesman_track'
    end

    resources :salesman_travels do
      collection do
        get 'zone'
        get 'map'
        post 'insert_sale'
        post 'insert_to_sale'
      end
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :logistics, path: :logistic do
    root "base#root"

app/controllers/admin_users/administrators_controller.rb
class AdminUsers::AdministratorsController < AdminUsers::BaseController
  authorize_resource class: false
  before_action :set_admin_user, only: [:edit, :update, :destroy]

  def index
    @admin_users = AdminUser.all.page(params[:page])
    # cat_colors = CategoryFilterGroup.search_name("color").map(&:id).to_a
    # colors = CategoryFilter.by_group(cat_colors)
    # colors.each do |c|
    #   ProductFeatureOption.create(name: c, name_en: c, product_feature_id: 1, group_id: 1)
    # end
    # groups = CategoryFilterGroup.qe_name('color')
    # groups.destroy_all
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_user_params)

    if @admin_user.save
      @admin_user.send_first_password_instructions
      flash[:success] = t('alert.saved_successfully')
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def edit
  end

  def update

    @admin_user.attributes = admin_user_params
    if @admin_user.save
      flash[:success] = t('alert.info_updated')
      redirect_to action: :index
    else
      render 'edit'
    end
  end

  def destroy
    @admin_user.destroy!

    flash[:success] = t('alert.deleted_successfully')
    render json: {status: 'ok'}
  end

  private

  def set_admin_user
    @admin_user = AdminUser.find(params[:id])
  end

  def admin_user_params
    params.require(:admin_user).permit(:email, :admin_permission_id)
  end
end

app/controllers/admin_users/ali_categories_controller.rb
#intall google-chrome-stable_current_x86_64.rpm
# google-chrome-stable-79.0.3945.130-1.x86_64

require 'capybara/dsl'
require 'selenium/webdriver'

Capybara.default_max_wait_time = 6
Capybara.default_driver = :selenium_chrome
Capybara.javascript_driver = :selenium_chrome
# Capybara.app_host = 'https://m.aliexpress.com'
Capybara.app_host = 'https://www.aliexpress.com'

class AdminUsers::BankLoginsController < AdminUsers::BaseController
  include Capybara::DSL

  def login
    Capybara.reset_sessions!
    visit('https://login.aliexpress.com')
    find('#fm-login-id').set('ariwiseo@gmail.com')
    find('#fm-login-password').set('marketpass1234')
    # click_button 'Sign In'
    # page.has_link?('all-wholesale-products.html')
  end

  def statement
    categories = AliCategory.none_check
    categories.each {|category|
      puts category.name
      visit_link(category, true)
      sleep_visit
    }

  end

  def sleep_visit
    rl = rand(60..90)
    uld = rl % 5
    rl = rl / 5
    (1..rl).each do |i|
      print "#{(i * 5)} "
      STDOUT.flush
      sleep(5)
    end
    sleep(uld)
    puts ""

  end

  def visit_link(category, has_child)
    visit(category.link)
    page.has_content?(category.name)

    within("div.left-menu-container") do
      left_div = page.find("div.left-refine-container", match: :first)

      left_div.all('div.refine-block').each {|fl|
        cls = fl[:class]
        if cls.include?('category')
          if has_child && fl.has_css?('ul.child-menu')
            ul = fl.find(('ul.child-menu'))
            ul.all('li').each {|li|
              a = li.first('a')
              category.sub_categories << AliCategory.new(name: a.text, link: a[:href].gsub('https://www.aliexpress.com', ''))
            }
          end
        elsif cls.include?('custom-text') || cls.include?('custom-img')
          if fl.has_css?('div.show-more')
            fl.first('div.show-more').click
          end

          is_img = cls.include?('custom-img')
          group_name = fl.find('div.title').text

          prod_group = AliFilterGroup.by_name(group_name).order_by
          name_mn = nil
          mn_change = false
          mn_prod = false
          if prod_group.present?
            fg = prod_group.first
            if fg.name_mn.present?
              name_mn = fg.name_mn
            end
            mn_change = fg.mn_change
            mn_prod = fg.prod
          end

          filter_group = AliFilterGroup.new(ali_category: category, name: group_name, name_mn: name_mn, mn_change: mn_change, prod: mn_prod)

          ul = fl.find("ul.inner-item", match: :first)
          ul.all('li').each {|li|
            filter = AliFilter.new(ali_filter_group: filter_group)
            if is_img
              filter.img = li.first('img')[:src]
              filter.mn_change = true
            else
              filter_name = li[:title]
              prod_filter = AliFilter.by_name(filter_name).order_by
              if prod_filter.present?
                ff = prod_filter.first
                if ff.name_mn.present?
                  filter.name_mn = ff.name_mn
                end
                filter.mn_change = ff.mn_change
                filter.prod = ff.prod
              end

              filter.name = filter_name
            end
            filter_group.filters << filter
          }

          category.filter_groups << filter_group
        end
      }
      category.checked = true
      category.save
    end
  end

end

app/controllers/admin_users/base_controller.rb
class AdminUsers::BaseController < ApplicationController
  layout 'admin'

  before_action do
    set_locale
    authenticate_admin_user!
    redirect_to admin_passwords_edit_password_path if current_admin_user.password_is_reset
  end

  def routing_error
    redirect_to admin_users_root_path
  end

  def set_locale
    I18n.locale = params[:locale] || :mn
  end
end

app/controllers/admin_users/logistics_controller.rb
class AdminUsers::LogisticsController < AdminUsers::BaseController
  load_and_authorize_resource
  before_action :set_logistic, only: [:show, :edit, :update, :destroy]

  def index
    @semail = params[:email]
    @sname = params[:name]
    @sphone = params[:phone]
    @logistics = Logistic.search(@sname, @semail, @sphone).page(params[:page])
    cookies[:logistic_page_number] = params[:page]
  end

  def new
    @logistic = Logistic.new
  end

  def create
    @logistic = Logistic.new(logistic_params)

    if @logistic.save
      @logistic.send_first_password_instructions
      flash[:success] = t('alert.saved_successfully')
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @logistic.attributes = logistic_params
    if @logistic.save
      flash[:success] = t('alert.info_updated')
      redirect_to :action => 'show', id: @logistic.id
    else
      render 'edit'
    end
  end

  def destroy
    @logistic.destroy!
    flash[:success] = t('alert.deleted_successfully')
    redirect_to action: :index
  end

  #
  # def logistic_sign_in
  #   sign_in :logistic, @logistic
  #   redirect_to logistics_root_path
  # end

  private

  def set_logistic
    @logistic = Logistic.find(params[:id])
  end

  def logistic_params
    params.require(:logistic).permit(:surname, :name, :gender, :email, :phone,
                                     logistic_permission_rels_attributes: [:id, :logistic_permission_id, :role, :_destroy])
  end
end

app/controllers/admin_users/passwords_controller.rb
class AdminUsers::PasswordsController < Devise::PasswordsController
  def after_sign_in_path_for(resource_or_scope)
    admin_users_root_path
  end
end

app/controllers/admin_users/sessions_controller.rb
class AdminUsers::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource_or_scope)
    admin_users_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_admin_user_session_path
  end
end

app/controllers/logistics/passwords_controller.rb
class Logistics::PasswordsController < Devise::PasswordsController
  def after_sign_in_path_for(resource_or_scope)
    logistics_root_path
  end
end

app/views/admin_users/logistics/_form.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1><%= t('activerecord.models.logistic') + t(@logistic.persisted? ? 'titles.edit' : 'titles.add') %></h1>
  </section>
  <section class="content">
    <div class="box box-info">
      <%= form_with model: @logistic, url: @logistic.persisted? ? admin_users_logistic_path : admin_users_logistics_path, method: @logistic.persisted? ? :patch : :post, local: true, :html => {class: 'form-horizontal'} do |f| %>
        <%= form_body do %>
          <div class="form-group">
            <%= f.label :surname, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@logistic, :surname) %>">
              <%= field_errors(@logistic, :surname) %>
              <%= f.text_field :surname, class: 'form-control', placeholder: t('activerecord.attributes.logistic.surname') %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :name, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@logistic, :name) %>">
              <%= field_errors(@logistic, :name) %>
              <%= f.text_field :name, class: 'form-control', placeholder: t('activerecord.attributes.logistic.name') %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :gender, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 radio-group p-t-5 <%= get_error_class(@logistic, :gender) %>">
              <%= field_errors(@logistic, :gender) %>
              <%= f.collection_radio_buttons :gender, Operator.genders_i18n, :first, :second do |b| %>
                <%= b.radio_button %>&nbsp;&nbsp;<%= b.text %> &nbsp;&nbsp;
              <% end %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@logistic, :email) %>">
              <%= get_user_field_errors(@logistic, :email) %>
              <%= f.email_field :email, class: 'form-control', placeholder: t('activerecord.attributes.logistic.email'), disabled: @logistic.persisted? %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :phone, class: 'col-sm-3 control-label' %>
            <div class="col-sm-9 <%= get_error_class(@logistic, :phone) %>">
              <%= field_errors(@logistic, :phone) %>
              <%= f.text_field :phone, class: 'form-control', placeholder: t('activerecord.attributes.logistic.phone') %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :logistic_permission_rels, class: 'col-sm-3 control-label' %>

            <div class="col-sm-9 cocoon-nested-form">
              <div class="<%= get_error_class(@logistic, :logistic_permission_rels) %>">
                <%= field_errors(@logistic, :logistic_permission_rels) %>
                <table class="table table-bordered" id="tb_logistic_permission_rels">
                  <tr>
                    <th width="45%"><%= t('activerecord.attributes.logistic_permission_rel.logistic_permission_id') %></th>
                    <th width="45%"><%= t('activerecord.attributes.logistic_permission_rel.role') %></th>
                    <th width="50px"></th>
                  </tr>
                  <%= f.fields_for :logistic_permission_rels do |rel| %>
                    <%= render 'logistic_permission_rel_fields', f: rel %>
                  <% end %>
                </table>
              </div>
              <div class="links item_append">
                <%= link_to_add_association f, :logistic_permission_rels, data: {association_insertion_node: '#tb_logistic_permission_rels', association_insertion_method: :append} do %>
                  <%= nested_add_btn %>
                <% end %>
              </div>
            </div>
          </div>


          <div class="action-buttons">
            <%= f.submit t('controls.button.save'), class: 'btn btn-warning' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>
</div>

app/views/admin_users/logistics/_logistic_permission_rel_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= field_errors f.object, :logistic_permission_id %>
    <%= f.collection_select :logistic_permission_id, LogisticPermission.by_queue, :id, :description,
                            {:prompt => t('controls.select.none')}, {class: 'form-control selectpicker'} %>
  </td>
  <td>
    <%= field_errors f.object, :role %>
    <%= f.select :role, LogisticPermissionRel.roles.keys.map {|k| [LogisticPermissionRel.roles_i18n[k], k]}, {:prompt => t('controls.select.none')}, {class: 'form-control selectpicker'} %>
  </td>
  <td class="va-mid remove">
    <%= link_to_remove_association f, data: {confirm: t('are_you_sure')} do %>
      <%= nested_remove_btn %>
    <% end %>
  </td>
</tr>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker('refresh');
    })
</script>

app/views/admin_users/logistics/index.html.erb
<div class="content-wrapper">
  <div class="col-md-12 m-t-10 m-b-10">
    <div class="row">
      <%= form_with url: admin_users_logistics_path, method: "get", class: 'form-horizontal', local: true do |f| %>
        <div class="col-md-3 search">
          <%= text_field_tag :name, @sname, {class: 'form-control search', placeholder: t('filters.name')} %>
        </div>
        <div class="col-md-3 search">
          <%= text_field_tag :email, @semail, {class: 'form-control search', placeholder: t('filters.email')} %>
        </div>
        <div class="col-md-3 search">
          <%= text_field_tag :phone, @sphone, {class: 'form-control search', placeholder: t('filters.phone')} %>
        </div>
        <div class="col-md-3 search">
          <%= submit_tag t('controls.button.searching') + " (" + @logistics.total_count.to_s + ")", :class => 'btn blck-btn pull-left' %>

          <% is_manage = can? :manage, Logistic %>
          <% if is_manage %>
            <%= link_to t('controls.button.create'), new_admin_users_logistic_path, class: 'btn btn-warning pull-right' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <section class="content container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <%= render 'layouts/flash_message' %>

          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <tr>
                <th class="th-center va-mid"><%= t('activerecord.attributes.logistic.surname') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.logistic.name') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.logistic.gender') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.logistic.email') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.logistic.phone') %></th>
              </tr>
              <% @logistics.each do |logistic| %>
                <tr>
                  <td class="va-mid"><%= logistic.surname %></td>
                  <td class="va-mid underline"><%= link_to logistic.name, admin_users_logistic_path(logistic) %></td>
                  <td class="va-mid"><%= logistic.gender_i18n %></td>
                  <td class="va-mid"><%= logistic.email %></td>
                  <td class="td-center va-mid"><%= logistic.phone %></td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
        <%= paginate @logistics %>
      </div>
    </div>
  </section>
</div>

app/views/admin_users/logistics/show.html.erb
<div class="content-wrapper">
  <%= render 'layouts/flash_message' %>

  <section class="content-header align-left padding-15">
    <h1> <%= t('activerecord.models.logistic') %> </h1>
  </section>

  <div class="action-buttons">
    <% if can? :manage, Logistic %>
      <%= link_to t('controls.button.edit'), edit_admin_users_logistic_path(@logistic), class: 'btn btn-info' %>
      <%= link_to t('controls.button.delete'), admin_users_logistic_path(@logistic), method: :delete, data: {confirm: t('are_you_sure')}, class: 'btn btn-danger' %>
    <% end %>
    <%= link_to t('titles.back_to_list'), admin_users_logistics_path(page: cookies[:logistic_page_number]), {class: "btn blck-btn"} %>
  </div>
  <%= show_body do %>
    <div class="box">
      <div class="box-body table-responsive no-padding">
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.logistic.surname') %> :</div>
          <div class="col-data"><%= @logistic.surname %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.logistic.name') %> :</div>
          <div class="col-data"><%= @logistic.name %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.logistic.gender') %> :</div>
          <div class="col-data"><%= @logistic.gender_i18n %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.logistic.email') %> :</div>
          <div class="col-data"><%= @logistic.email %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.logistic.phone') %> :</div>
          <div class="col-data"><%= @logistic.phone.presence || :'---' %></div>
        </div>
        <div class="m30">
          <div class="align-left"><%= t('activerecord.attributes.logistic_permission_rel.logistic_permission_id') %> :</div>
          <div class="col-data">
            <table class="table table-bordered">
              <thead>
              <tr>
                <th><%= t('activerecord.attributes.logistic_permission_rel.logistic_permission_id') %></th>
                <th><%= t('activerecord.attributes.logistic_permission_rel.role') %></th>
              </tr>
              </thead>
              <tbody>
              <% @logistic.logistic_permission_rels.each do |r| %>
                <tr>
                  <td class="va-mid"><%= r.logistic_permission.description %></td>
                  <td class="va-mid"><%= r.role_i18n %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>