config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'SysUser', at: '/auth'
    end
    namespace :salesman do
      mount_devise_token_auth_for 'Salesman', at: '/auth'
    end
    namespace :user do
      mount_devise_token_auth_for 'User', at: '/auth'
    end
  end
  mount ActionCable.server, at: '/cable'
  mount API::Base => '/api'

  get 'fb_comment_path', to: 'application#fb_comment_path'
  root 'users/base#root'

  post 'search_product', to: 'application#search_product'
  post 'search_fb_answer', to: 'application#search_fb_answer'
  patch 'get_product_features', to: 'application#get_product_features'

  devise_for :admin_users, path: :admin, controllers: {
      sessions: 'admin_users/sessions',
      registrations: 'admin_users/registrations',
      passwords: 'admin_users/passwords'
  }

  devise_scope :admin_user do
    get 'admin/passwords/edit_password', to: 'admin_users/registrations#edit_password'
    patch 'admin/passwords', to: 'admin_users/registrations#update_password'
  end

  devise_for :users, path: :user, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords',
  }

  devise_scope :user do
    get 'user/passwords/edit_password', to: 'users/registrations#edit_password'
    patch 'user/passwords', to: 'users/registrations#update_password'
  end

  devise_for :operators, path: :operator, controllers: {
      registrations: 'operators/registrations',
      sessions: 'operators/sessions',
      passwords: 'operators/passwords',
  }

  devise_scope :operator do
    get 'operator/passwords/edit_password', to: 'operators/registrations#edit_password'
    patch 'operator/passwords', to: 'operators/registrations#update_password'
  end

  devise_for :logistics, path: :logistic, controllers: {
      registrations: 'logistics/registrations',
      sessions: 'logistics/sessions',
      passwords: 'logistics/passwords',
  }

  devise_scope :logistic do
    get 'logistic/passwords/edit_password', to: 'logistics/registrations#edit_password'
    patch 'logistic/passwords', to: 'logistics/registrations#update_password'
  end


  namespace :admin_users, path: :admin do
    root 'users#index'
    resources :administrators, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :users, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :logistics, only: [:index, :create, :new, :show, :edit, :update, :destroy]

    namespace :bank_logins do
      get 'login'
    end

    namespace :facebooks do
      get 'posts'
      get 'attachments'
      get 'to_archives'
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :users, path: :user do
    root "base#root"
    get "panel", to: 'pages#panel'
    post 'uploads' => 'uploads#create'

    namespace :calc do
      get 'vrptw'
    end

    resources :product_categories, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :customers, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :customer_warehouses, only: [:create, :new, :edit, :update, :destroy]
    resources :customer_imports, only: [:new, :create] do
      collection do
        post 'customer_warehouse'
      end
    end
    resources :product_feature_groups, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :product_features, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :product_feature_options, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :category_filter_groups, only: [:index, :create, :new, :show, :edit, :update, :destroy], path: "category/filters"
    resources :product_discounts, only: [:create, :new, :edit, :update, :destroy]
    resources :product_feature_items, only: [:create, :new, :destroy] do
      collection do
        get 'balance'
        post 'get_feature_items'
        get 'set_balance'
        post 'load_features'
        post 'itoms'
        patch 'update_feature'
      end
    end
    resources :products, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        patch 'get_product_category_children'
        patch 'form_price'
        patch 'form_information'
        patch 'form_image_video'
        patch 'form_package'
        post 'technical_spec_items'
      end
    end
    resources :product_supply_orders, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
      collection do
        patch 'form_feature'
        post 'last_product_price'
        get 'to_product'
        get 'to_excel'
      end
    end
    resources :product_locations, only: [:index, :create, :new, :edit, :update, :destroy]

    get 'product_incomes/shipping_show/:id', to: 'product_incomes#shipping_show'
    resources :product_incomes do
      collection do
        patch 'get_location_children'
        patch 'get_supply_order_info'
        patch 'insert_shipping_ub'
        patch 'insert_half_ub'
        get 'locations'
        patch 'set_location'
        post 'search_products'
        post 'search_half_products'
        post 'search_supply_feature'
        post 'insert_sample_product'
        post 'income_logs'
        patch 'update_income_log'
      end
    end
    resources :operators, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :salesmen, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :ali_categories, only: [:index, :create, :show, :edit, :update, :destroy] do
      collection do
        patch 'set_prod'
        patch 'set_name_as_filter'
        get 'form_filter'
        patch 'update_filter'
      end
    end

    resources :bank_accounts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :bank_dealing_accounts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :brands, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :manufacturers, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :technical_specifications, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :size_instructions, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :fb_posts do
      collection do
        post 'download'
      end
    end
    resources :fb_comments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        patch 'hide'
      end
    end
    resources :fb_comment_archives, only: [:index, :show] do
      collection do
        get 'report'
        post 'get_message_url'
      end
    end
    resources :bank_transactions
    resources :store_transfers do
      collection do
        patch 'get_product_features'
        post 'get_product_balance'
      end
    end
    resources :direct_sales do
      collection do
        post 'get_product_balance'
      end
    end
    resources :sms_messages, only: [:index, :create, :new]
    namespace :delivery_reports do
      get 'index'
      get 'salary'
    end
    resources :sale_taxes, only: [:index, :create, :new, :edit, :update]
    resources :product_sales, only: [:index] do
      collection do
        post 'check_register'
        post 'tax'
        get 'report'
      end
    end

    namespace :product_reports do
      get 'track'
      get 'track_logs'
      post 'track_log'
    end

    namespace :supply_calculations do
      get 'supply_orders'
      get 'income_products'
      patch 'set_calculated'
      patch 'set_all_calculated'
      get 'for_invoice'
      get 'purchased_er'
      get 'received_er'
      get 'ship_ub'
      get 'calculate'
    end

    namespace :warehouse_reports do
      get 'daily'
      get 'products'
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :operators, path: :operator do
    root "base#root"

    resources :product_sales, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        post 'search_locations'
        post 'edit_location'
        post 'update_location'
        post 'search_khoroos'
        post 'get_last_location'
        post 'get_product_balance'
        patch 'update_status'
        post 'get_bonus'
        post 'next_status'
        post 'get_radius_sales'
      end
    end

    resources :fb_comments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        patch 'like'
        patch 'hide'
      end
    end
    resources :fb_comment_actions
    resources :fb_comment_archives, only: [:index, :show] do
      collection do
        get 'report'
        post 'get_message_url'
      end
    end

    resources :product_sale_calls, only: [:index, :new, :edit, :update, :show] do
      collection do
        post 'auto_save'
        post 'get_prev_sales'
        post 'check_sale_order'
      end
    end

    resources :bank_transactions, only: [:index]
    resources :sms_messages, only: [:index, :create, :new]
    resources :loc_districts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :bonus, only: [:index, :edit, :update, :destroy]
    resources :loc_khoroos, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :locations, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        post 'get_location'
      end
    end
    resources :location_zones
    namespace :distributing do
      get 'index'
      post 'set_travel'
      post 'travel_routes'
      post 'product_sales'
      post 'add_product_sale'
      post 'change_route_queue'
      patch 'remove_route'
      post 'distributing'
      post 'salesman_track'
    end

    resources :salesman_travels do
      collection do
        get 'zone'
        get 'map'
        post 'insert_sale'
        post 'insert_to_sale'
      end
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :logistics, path: :logistic do
    root "base#root"

app/models/logistic.rb
class Logistic < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,:registerable, and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :logistic_permission_rels, dependent: :destroy
  accepts_nested_attributes_for :logistic_permission_rels, allow_destroy: true

  after_destroy :destroy_email
  before_validation :generate_password, on: :create
  after_validation :remove_unnecessary_error_messages

  enum gender: {male: 0, female: 1}

  validates :surname, :name, :phone, presence: true, length: {maximum: 255}
  validates :gender, :logistic_permission_rels, presence: true
  validates :email, uniqueness: {conditions: -> {with_deleted}}

  scope :search, ->(search_name, search_email, search_phone) {
    items = created_at_desc
    items = items.where('name LIKE :value OR surname LIKE :value', value: "%#{search_name}%") if search_name.present?
    items = items.where('email = ?', search_email) if search_email.present?
    items = items.where('phone = ?', search_phone) if search_phone.present?
    items
  }

  scope :created_at_desc, -> {
    order(created_at: :desc)
  }

  scope :order_name, -> {
    order(:name)
  }

  def send_first_password_instructions
    send_devise_notification(:first_password_instructions, password, subject: 'Нэвтрэх нууц үгийн мэдээлэл', to: email)
  end

  protected

  def devise_mailer
    LogisticMailer
  end

  private

  def generate_password
    if password.blank?
      self.password_is_reset = true if self.password_is_reset != false
      self.password = Devise.friendly_token(6)
    end
  end

  def destroy_email
    email_bits = email.split('@')
    update!(email: "#{email_bits[0]}_#{Time.zone.now.to_i}@#{email_bits[1]}")
  end

  def remove_unnecessary_error_messages
    errors.messages.each {|key, val| val.uniq!}
  end
end

app/models/shipping_ub.rb
class ShippingUb < ApplicationRecord
  belongs_to :logistic

  has_many :shipping_ub_products, dependent: :destroy
  has_many :shipping_ub_boxes, dependent: :destroy
  has_many :shipping_ub_samples, dependent: :destroy
  has_many :products, through: :shipping_ub_products
  has_many :product_income_products, through: :shipping_ub_products

  accepts_nested_attributes_for :shipping_ub_boxes, allow_destroy: true
  accepts_nested_attributes_for :shipping_ub_samples, allow_destroy: true

  enum s_type: {simple: 0, urgent: 1}

  before_validation :check_ub_products
  validates :date, :s_type, presence: true

  with_options :unless => Proc.new {|m| m.shipping_ub_samples.present?} do
    validates :shipping_ub_boxes, :length => {:minimum => 1}
  end
  with_options :unless => Proc.new {|m| m.shipping_ub_boxes.present?} do
    validates :shipping_ub_samples, :length => {:minimum => 1}
  end
  attr_accessor :number

  scope :order_created_at, -> {
    order(:date)
  }

  scope :search, ->(start, finish, product_name) {
    items = order_created_at
    items = items.joins(:products)
                .where('products.code LIKE :value OR products.n_name LIKE :value OR products.c_name LIKE :value', value: "%#{product_name}%").group("id") if product_name.present?
    items = items.where('? <= date AND date <= ?', start.to_time, finish.to_time + 1.days) if start.present? && finish.present?
    items
  }

  def shipping_ub_features
    shipping_ub_products
        .sum(:quantity)
  end

  def cargo_price
    shipping_ub_products.sum(:cost) + shipping_ub_samples.sum(:cost)
  end

  def cargo
    shipping_ub_products.sum(:cargo) + shipping_ub_samples.sum(:number)
  end

  def ub_income_cargo
    product_income_products.sum(:cargo)
  end

  def product_names
    names = ""
    products.each_with_index {|product, index|
      if index > 0
        names += ", "
      end
      names += product.c_name if product.c_name.present?
    }
    names
  end

  private

  def check_ub_products
    if shipping_ub_samples.present?
      shipping_ub_boxes.each do |box|
        unless box.shipping_ub_products.present?
          box.destroy
        end
      end
    end
  end
end

app/controllers/admin_users/logistics_controller.rb
class AdminUsers::LogisticsController < AdminUsers::BaseController
  load_and_authorize_resource
  before_action :set_logistic, only: [:show, :edit, :update, :destroy]

  def index
    @semail = params[:email]
    @sname = params[:name]
    @sphone = params[:phone]
    @logistics = Logistic.search(@sname, @semail, @sphone).page(params[:page])
    cookies[:logistic_page_number] = params[:page]
  end

  def new
    @logistic = Logistic.new
  end

  def create
    @logistic = Logistic.new(logistic_params)

    if @logistic.save
      @logistic.send_first_password_instructions
      flash[:success] = t('alert.saved_successfully')
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @logistic.attributes = logistic_params
    if @logistic.save
      flash[:success] = t('alert.info_updated')
      redirect_to :action => 'show', id: @logistic.id
    else
      render 'edit'
    end
  end

  def destroy
    @logistic.destroy!
    flash[:success] = t('alert.deleted_successfully')
    redirect_to action: :index
  end

  #
  # def logistic_sign_in
  #   sign_in :logistic, @logistic
  #   redirect_to logistics_root_path
  # end

  private

  def set_logistic
    @logistic = Logistic.find(params[:id])
  end

  def logistic_params
    params.require(:logistic).permit(:surname, :name, :gender, :email, :phone,
                                     logistic_permission_rels_attributes: [:id, :logistic_permission_id, :role, :_destroy])
  end
end

app/controllers/logistics/base_controller.rb
class Logistics::BaseController < ApplicationController
  layout 'logistic'

  before_action do
    set_locale
    authenticate_logistic!
    redirect_to logistic_passwords_edit_password_path if current_logistic.password_is_reset
  end

  def root
    redirect_to logistics_supply_orders_path(order_type: 'basic')
  end

  def routing_error
    redirect_to logistics_supply_orders_path
  end

  def set_locale
    I18n.locale = params[:locale] || current_logistic.present? ? current_logistic.lang : 'mn'
  end

end

app/controllers/logistics/passwords_controller.rb
class Logistics::PasswordsController < Devise::PasswordsController
  def after_sign_in_path_for(resource_or_scope)
    logistics_root_path
  end
end

app/controllers/logistics/registrations_controller.rb
class Logistics::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :authenticate_scope!, only: [:edit_password, :update_password]

  def new
    redirect_to logistics_root_path
  end

  def create
    redirect_to logistics_root_path
  end

  def edit_password
    set_minimum_password_length
  end

  def update_password
    if self.resource.update(password_params)
      # Sign in the logistic by passing validation in case their password changed
      bypass_sign_in resource
      redirect_to logistics_root_path
    else
      render 'edit_password'
    end
  end

  private

  def password_params
    permitted = params.require(:logistic).permit(:password, :password_confirmation)
    permitted.merge!({:password_is_reset => false})
  end
end

app/controllers/logistics/sessions_controller.rb
class Logistics::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource_or_scope)
    logistics_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_logistic_session_path
  end
end

app/views/logistics/shipping_ubs/_index.html.erb
<% content_for :stylesheets do -%>
  <%= stylesheet_link_tag "list" %>
<% end %>
<div class="content-wrapper">
  <div class="col-md-12 m-t-10 m-b-10">
    <div class="row">
      <%= form_with url: is_logistic ? logistics_shipping_ubs_path : shipping_users_product_incomes_path, method: "get", class: 'form-horizontal', local: true do |f| %>
        <div class="col-md-4 search">
          <div id="search-date" class="form-control search">
            <i class="fa fa-calendar fa-lg p-r-0"></i>
            <span><%= t("filters.by_date") %>...</span>
            <%= f.hidden_field :by_start, value: @by_start %>
            <%= f.hidden_field :by_end, value: @by_end %>
          </div>
        </div>
        <div class="col-md-4 search">
          <%= text_field_tag :product_name, @product_name, {class: 'form-control search', placeholder: t('activerecord.attributes.product_supply_order.product_name')} %>
        </div>
        <div class="col-md-4 search">
          <%= submit_tag t('controls.button.searching') + " (" + @shipping_ubs.total_count.to_s + ")", :class => 'btn blck-btn pull-left' %>
          <% if is_logistic && (can? :manage, ShippingUb) %>
            <%= link_to t('controls.button.create'), new_logistics_shipping_ub_path, class: 'btn btn-warning pull-right' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <section class="content container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <%= render 'layouts/flash_message' %>

          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <thead>
              <tr>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_ub.number') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_ub.date') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_er.shipping_er_products') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_ub.shipping_ub_features') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_ub_product.cargo') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_ub.ub_income_cargo') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_ub_product.cost') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_ub.s_type') %></th>
                <th class="th-center va-mid"><%= t('activerecord.attributes.shipping_ub.description') %></th>
              </tr>
              </thead>
              <% @shipping_ubs.each do |shipping_ub| %>
                <tr>
                  <td class="va-mid underline text-center"><%= link_to show_id(shipping_ub.id), is_logistic ? logistics_shipping_ub_path(shipping_ub) : "/user/product_incomes/shipping_show/#{shipping_ub.id}" %></td>
                  <td class="va-mid"><%= shipping_ub.date.strftime('%F') %></td>
                  <td class="va-mid"><%= shipping_ub.product_names %></td>
                  <td class="va-mid text-center"><%= shipping_ub.shipping_ub_features %></td>
                  <td class="va-mid text-center"><%= shipping_ub.cargo %></td>
                  <td class="va-mid text-center"><%= shipping_ub.ub_income_cargo %></td>
                  <td class="va-mid"><%= get_currency(shipping_ub.cargo_price, Const::CURRENCY[0], 3) %></td>
                  <td class="va-mid text-center"><%= shipping_ub.s_type_i18n %></td>
                  <td class="va-mid text-center"><%= shipping_ub.description %></td>
                </tr>
              <% end %>
              <% shipping_ub_product_ids = ShippingUbProduct.by_shipping_ub_id(@shipping_ubs_all.pluck(:id)).pluck(:id)%>
              <tr>
                <td class="va-mid underline" colspan="3"><strong>Нийт: <%= @shipping_ubs_all.count%></strong></td>
                <td class="va-mid text-center"><%= ShippingUbProduct.by_shipping_ub_id(@shipping_ubs_all.pluck(:id)).pluck(:quantity).sum(&:to_i) %></td>
                <td class="va-mid text-center"><%= ShippingUbProduct.by_shipping_ub_id(@shipping_ubs_all.pluck(:id)).pluck(:cargo).sum(&:to_i) %></td>
                <td class="va-mid text-center"><%= ProductIncomeProduct.by_shipping_ub_product_id(shipping_ub_product_ids).pluck(:cargo).sum(&:to_i) %></td>
                <td class="va-mid"><%= get_currency(ShippingUbProduct.by_shipping_ub_id(@shipping_ubs_all.pluck(:id)).pluck(:cost).sum(&:to_f), Const::CURRENCY[0], 3)%></td>
                <td class="va-mid text-center"><%=  %></td>
                <td class="va-mid text-center"><%=  %></td>
              </tr>
            </table>
          </div>
        </div>
        <%= paginate @shipping_ubs %>
      </div>
    </div>
  </section>
</div>
<%= render 'shared/date-range', search_field_id: 'search-date', start_id: 'by_start', finish_id: 'by_end' %>

app/views/logistics/shipping_ubs/_show.html.erb
<% content_for :stylesheets do -%>
  <%= stylesheet_link_tag "show" %>
<% end %>
<div class="content-wrapper">
  <%= render 'layouts/flash_message' %>
  <section class="content-header align-left padding-15">
    <h1><%= t('activerecord.models.shipping_ub') %></h1>
  </section>

  <div class="action-buttons">
    <% if is_logistic %>
      <% if can? :manage, ShippingUb %>
        <%= link_to t('controls.button.edit'), edit_logistics_shipping_ub_path(@shipping_ub), class: 'btn btn-info' %>
      <% end %>
      <%= link_to t('titles.back_to_list'), logistics_shipping_ubs_path(page: cookies[:shipping_ub_page_number]), {class: "btn blck-btn"} %>
    <% elsif can? :manage, ShippingUb %>
      <%= link_to t('titles.product_incomes'), new_users_product_income_path(id: @shipping_ub.id), class: 'btn btn-warning' %>
    <% end %>
  </div>
  <%= show_body do %>
    <div class="box">
      <div class="box-body table-responsive no-padding">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-3">
              <b><%= t('activerecord.attributes.shipping_ub.date') %>:</b> <%= @shipping_ub.date.strftime('%F') %>
            </div>
            <div class="col-md-3">
              <b><%= t('activerecord.attributes.shipping_ub.number') %>:</b> <%= show_id @shipping_ub.id %>
            </div>
            <div class="col-md-3">
              <b><%= t('activerecord.attributes.shipping_ub.s_type') %>:</b> <%= @shipping_ub.s_type_i18n %>
            </div>
            <div class="col-md-3">
              <b><%= t('activerecord.attributes.shipping_ub.description') %>:</b> <%= @shipping_ub.description %>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <table class="table table-bordered t-list m-t-10 table-hover">
            <thead>
            <tr>
              <th colspan="5"></th>
              <th colspan="3" class="text-center"><%= t('titles.received') %></th>
              <th colspan="3" class="text-center"><%= t('titles.consignment') %></th>
            </tr>
            <tr>
              <th class="va-mid"><%= t('activerecord.attributes.shipping_er_product.product_name') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_er_product.product_code') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_er_product.product_image') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_er_product.product_feature') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_ub_product.product_bought') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_ub_product.quantity') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_er_product.cargo') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_ub_product.at_er') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_ub_product.quantity') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_ub_product.cargo') %></th>
              <th class="va-mid text-center"><%= t('activerecord.attributes.shipping_ub_product.cost') %></th>
            </tr>
            </thead>
            <tbody>
            <% @shipping_ub.shipping_ub_boxes.each_with_index {|box, b_i| %>
              <% if box.is_box? %>
                <tr>
                  <td class="2" colspan="11"><%= t('activerecord.models.shipping_ub_box') %>: <%= box.number %></td>
                </tr>
              <% end %>
              <% box.shipping_ub_products.each_with_index {|ub, index|
                product = ub.product
                shipping_er_product = ub.shipping_er_product %>
                <tr>
                  <td class="va-mid"><%= product.cn_name %></td>
                  <td class="va-mid"><%= product.code %></td>
                  <td class="va-mid text-center">
                    <% if product.picture.present? %>
                      <%= link_to product.picture.url, "data-lightbox": "roadtrip" do %>
                        <%= t('titles.view') %>
                      <% end %>
                    <% end %>
                  </td>
                  <td class="va-mid text-center"><%= shipping_er_product.shipping_er_features.count %></td>
                  <td class="va-mid text-center"><%= shipping_er_product.product_bought %></td>
                  <td class="va-mid text-center"><%= shipping_er_product.quantity %></td>
                  <td class="va-mid text-center"><%= shipping_er_product.cargo %></td>
                  <td class="va-mid text-center"><%= shipping_er_product.shipping_er.date.strftime('%F') %></td>
                  <td class="va-mid text-center"><%= ub.quantity %></td>
                  <td class="va-mid text-center"><%= ub.cargo %></td>
                  <% if box.is_box?
                       if index == 0 %>
                      <td class="va-mid text-center" rowspan="<%= box.shipping_ub_products.count %>"><%= get_currency(box.cost, Const::CURRENCY[0], 3) %></td>
                    <% end
                       else %>
                    <td class="va-mid text-center"><%= get_currency(ub.cost, Const::CURRENCY[0], 3) %></td>
                  <% end %>
                </tr>
              <% }
                 } %>
            </tbody>
          </table>
        </div>
        <% if @shipping_ub.shipping_ub_samples.present? %>
          <div class="col-md-12">
            <table class="table table-bordered t-list m-t-10 table-hover">
              <thead>
              <tr>
                <th width="30px">#</th>
                <th><%= t('activerecord.attributes.shipping_ub.shipping_ub_samples') %> <%= t('activerecord.attributes.shipping_ub_sample.number') %></th>
                <th><%= t('activerecord.attributes.shipping_ub_sample.cost') %></th>
              </tr>
              </thead>
              <tbody>
              <% @shipping_ub.shipping_ub_samples.each_with_index {|s, index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= s.number %></td>
                  <td><%= get_currency(s.cost, Const::CURRENCY[0], 3) %></td>
                </tr>
              <% } %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/logistics/shipping_ubs/index.html.erb
<%= render 'index', is_logistic: true %>