config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'SysUser', at: '/auth'
    end
    namespace :salesman do
      mount_devise_token_auth_for 'Salesman', at: '/auth'
    end
    namespace :user do
      mount_devise_token_auth_for 'User', at: '/auth'
    end
  end
  mount ActionCable.server, at: '/cable'
  mount API::Base => '/api'

  get 'fb_comment_path', to: 'application#fb_comment_path'
  root 'users/base#root'

  post 'search_product', to: 'application#search_product'
  post 'search_fb_answer', to: 'application#search_fb_answer'
  patch 'get_product_features', to: 'application#get_product_features'

  devise_for :admin_users, path: :admin, controllers: {
      sessions: 'admin_users/sessions',
      registrations: 'admin_users/registrations',
      passwords: 'admin_users/passwords'
  }

  devise_scope :admin_user do
    get 'admin/passwords/edit_password', to: 'admin_users/registrations#edit_password'
    patch 'admin/passwords', to: 'admin_users/registrations#update_password'
  end

  devise_for :users, path: :user, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords',
  }

  devise_scope :user do
    get 'user/passwords/edit_password', to: 'users/registrations#edit_password'
    patch 'user/passwords', to: 'users/registrations#update_password'
  end

  devise_for :operators, path: :operator, controllers: {
      registrations: 'operators/registrations',
      sessions: 'operators/sessions',
      passwords: 'operators/passwords',
  }

  devise_scope :operator do
    get 'operator/passwords/edit_password', to: 'operators/registrations#edit_password'
    patch 'operator/passwords', to: 'operators/registrations#update_password'
  end

  devise_for :logistics, path: :logistic, controllers: {
      registrations: 'logistics/registrations',
      sessions: 'logistics/sessions',
      passwords: 'logistics/passwords',
  }

  devise_scope :logistic do
    get 'logistic/passwords/edit_password', to: 'logistics/registrations#edit_password'
    patch 'logistic/passwords', to: 'logistics/registrations#update_password'
  end


  namespace :admin_users, path: :admin do
    root 'users#index'
    resources :administrators, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :users, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :logistics, only: [:index, :create, :new, :show, :edit, :update, :destroy]

    namespace :bank_logins do
      get 'login'
    end

    namespace :facebooks do
      get 'posts'
      get 'attachments'
      get 'to_archives'
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :users, path: :user do
    root "base#root"
    get "panel", to: 'pages#panel'
    post 'uploads' => 'uploads#create'

    namespace :calc do
      get 'vrptw'
    end

    resources :product_categories, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :customers, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :customer_warehouses, only: [:create, :new, :edit, :update, :destroy]
    resources :customer_imports, only: [:new, :create] do
      collection do
        post 'customer_warehouse'
      end
    end
    resources :product_feature_groups, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :product_features, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :product_feature_options, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :category_filter_groups, only: [:index, :create, :new, :show, :edit, :update, :destroy], path: "category/filters"
    resources :product_discounts, only: [:create, :new, :edit, :update, :destroy]
    resources :product_feature_items, only: [:create, :new, :destroy] do
      collection do
        get 'balance'
        post 'get_feature_items'
        get 'set_balance'
        post 'load_features'
        post 'itoms'
        patch 'update_feature'
      end
    end
    resources :products, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        patch 'get_product_category_children'
        patch 'form_price'
        patch 'form_information'
        patch 'form_image_video'
        patch 'form_package'
        post 'technical_spec_items'
      end
    end
    resources :product_supply_orders, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
      collection do
        patch 'form_feature'
        post 'last_product_price'
        get 'to_product'
        get 'to_excel'
      end
    end
    resources :product_locations, only: [:index, :create, :new, :edit, :update, :destroy]

    get 'product_incomes/shipping_show/:id', to: 'product_incomes#shipping_show'
    resources :product_incomes do
      collection do
        patch 'get_location_children'
        patch 'get_supply_order_info'
        patch 'insert_shipping_ub'
        patch 'insert_half_ub'
        get 'locations'
        patch 'set_location'
        post 'search_products'
        post 'search_half_products'
        post 'search_supply_feature'
        post 'insert_sample_product'
        post 'income_logs'
        patch 'update_income_log'
      end
    end
    resources :operators, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :salesmen, only: [:index, :create, :new, :show, :edit, :update, :destroy]
    resources :ali_categories, only: [:index, :create, :show, :edit, :update, :destroy] do
      collection do
        patch 'set_prod'
        patch 'set_name_as_filter'
        get 'form_filter'
        patch 'update_filter'
      end
    end

    resources :bank_accounts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :bank_dealing_accounts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :brands, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :manufacturers, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :technical_specifications, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :size_instructions, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :fb_posts do
      collection do
        post 'download'
      end
    end
    resources :fb_comments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        patch 'hide'
      end
    end
    resources :fb_comment_archives, only: [:index, :show] do
      collection do
        get 'report'
        post 'get_message_url'
      end
    end
    resources :bank_transactions
    resources :store_transfers do
      collection do
        patch 'get_product_features'
        post 'get_product_balance'
      end
    end
    resources :direct_sales do
      collection do
        post 'get_product_balance'
      end
    end
    resources :sms_messages, only: [:index, :create, :new]
    namespace :delivery_reports do
      get 'index'
      get 'salary'
    end
    resources :sale_taxes, only: [:index, :create, :new, :edit, :update]
    resources :product_sales, only: [:index] do
      collection do
        post 'check_register'
        post 'tax'
        get 'report'
      end
    end

    namespace :product_reports do
      get 'track'
      get 'track_logs'
      post 'track_log'
    end

    namespace :supply_calculations do
      get 'supply_orders'
      get 'income_products'
      patch 'set_calculated'
      patch 'set_all_calculated'
      get 'for_invoice'
      get 'purchased_er'
      get 'received_er'
      get 'ship_ub'
      get 'calculate'
    end

    namespace :warehouse_reports do
      get 'daily'
      get 'products'
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :operators, path: :operator do
    root "base#root"

    resources :product_sales, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        post 'search_locations'
        post 'edit_location'
        post 'update_location'
        post 'search_khoroos'
        post 'get_last_location'
        post 'get_product_balance'
        patch 'update_status'
        post 'get_bonus'
        post 'next_status'
        post 'get_radius_sales'
      end
    end

    resources :fb_comments, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        patch 'like'
        patch 'hide'
      end
    end
    resources :fb_comment_actions
    resources :fb_comment_archives, only: [:index, :show] do
      collection do
        get 'report'
        post 'get_message_url'
      end
    end

    resources :product_sale_calls, only: [:index, :new, :edit, :update, :show] do
      collection do
        post 'auto_save'
        post 'get_prev_sales'
        post 'check_sale_order'
      end
    end

    resources :bank_transactions, only: [:index]
    resources :sms_messages, only: [:index, :create, :new]
    resources :loc_districts, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :bonus, only: [:index, :edit, :update, :destroy]
    resources :loc_khoroos, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :locations, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
      collection do
        post 'get_location'
      end
    end
    resources :location_zones
    namespace :distributing do
      get 'index'
      post 'set_travel'
      post 'travel_routes'
      post 'product_sales'
      post 'add_product_sale'
      post 'change_route_queue'
      patch 'remove_route'
      post 'distributing'
      post 'salesman_track'
    end

    resources :salesman_travels do
      collection do
        get 'zone'
        get 'map'
        post 'insert_sale'
        post 'insert_to_sale'
      end
    end

    match "*any", to: "base#routing_error", via: :all
  end

  namespace :logistics, path: :logistic do
    root "base#root"

app/controllers/admin_users/users_controller.rb
class AdminUsers::UsersController < AdminUsers::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @semail = params[:email]
    @sname = params[:name]
    @sphone = params[:phone]
    @users = User.search(@sname, @semail, @sphone).page(params[:page])
    cookies[:user_page_number] = params[:page]
  end

  def new
    @user = User.new
    @user.user_permission_rels << UserPermissionRel.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.send_first_password_instructions
      flash[:success] = t('alert.saved_successfully')
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @user.attributes = user_params
    if @user.save
      flash[:success] = t('alert.info_updated')
      redirect_to :action => 'show', id: @user.id
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy!
    flash[:success] = t('alert.deleted_successfully')
    redirect_to action: :index
  end

  # def user_sign_in
  #   sign_in :user, @user
  #   redirect_to users_root_path
  # end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:surname, :name, :gender, :email, :phone, :user_position_id,
                                 user_permission_rels_attributes: [:id, :user_permission_id, :role, :_destroy])
  end
end

app/controllers/api/user/base.rb
module API
  module USER
    class Base < Grape::API
      version 'user', using: :path
      format :json
      formatter :json, Grape::Formatter::Jbuilder

      # 例外ハンドル
      rescue_from ActiveRecord::RecordNotFound do |e|
        error!("Couldn't find data", 404)
      end

      rescue_from ActiveRecord::RecordNotUnique do |e|
        error!(e.message, 422)
      end

      rescue_from ActiveRecord::RecordInvalid do |e|
        error!(e.message, 422)
      end

      helpers do
        def authenticate_error!
          h = {'Access-Control-Allow-Origin' => "*",
               'Access-Control-Request-Method' => %w{GET POST OPTIONS}.join(",")}
          error!('You need to log in to use the app.', 401, h)
        end

        def current_user
          @resource
        end

        # header から認証に必要な情報を取得
        def authenticate_user!
          return if @resource
          uid = request.headers['Uid']
          token = request.headers['Access-Token']
          client = request.headers['Client']
          user = User.find_by(uid: uid)
          if user && user.valid_token?(token, client)
            @resource = user
          else
            @resource = nil
            authenticate_error!
          end
        end
      end

      mount API::USER::Passwords

      before do
        authenticate_user!
      end

      # mounts
      mount API::USER::Travels
      mount API::USER::Sales
      mount API::USER::Users
      mount API::USER::Locations
    end
  end
end

app/controllers/api/user/entities.rb
module API
  module USER
    module Entities

      class User < Grape::Entity
        expose :name, :uid, :email, :phone
      end

      class Salesman < Grape::Entity
        expose :id, :id_number, :surname, :name, :avatar, :avatar_tumb
      end

      class SalesmanTravels < Grape::Entity
        expose :id, :id_number, :load_at, :delivery_at, :sign_at, :load_at, :load_count, :load_sum
        expose :salesman, using: API::USER::Entities::Salesman
      end

      class ProductFeatureItem < Grape::Entity
        expose :id, :barcode, :product_id, :product_name, :name, :image_url, :quantity
      end

      class ProductWarehouse < Grape::Entity
        expose :id, :barcode, :name, :code, :desk, :feature, :image, :quantity, :load_at, :add_stock
      end

      class Products < Grape::Entity
        expose :id, :code, :name
      end

      class ProductFeatures < Grape::Entity
        expose :id, :name, :balance, :price
      end

      class SalesmanTravelRoutes < Grape::Entity
        expose :id, :queue, :loc_name, :phone, :product_count, :product_sale_id
      end

      class Notification < Grape::Entity
        expose :created_at, :title, :body_u, :avatar_s, :salesman_travel_id, :return_sign_id
      end

      class SalesmanReturnSign < Grape::Entity
        expose :id, :salesman_name, :products
      end

      class SalesmanReturn < Grape::Entity
        expose :id, :quantity, :product_code, :product_name, :product_image, :product_feature, :product_barcode
      end

      class ProductFeatureItemList < Grape::Entity
        expose :id, :barcode, :product_name, :name, :thumb_url, :image_url
      end

      class LocationTransferItem < Grape::Entity
        expose :id, :quantity, :transferred, :desk
        expose :product_feature_item, using: API::USER::Entities::ProductFeatureItemList
      end

      class LocationTransfer < Grape::Entity
        expose :id, :location_name
        expose :product_location_trans_items, using: API::USER::Entities::LocationTransferItem
      end

      class LocationTransferList < Grape::Entity
        expose :id, :location_name, :quantity, :transferred
      end

      class ProductLocation < Grape::Entity
        expose :name, :quantity
      end

      class TransferHistoryBySalesman < Grape::Entity
        expose :salesman_id, :salesman_name, :quantity
      end

      class ProductWarehouseUserSign < Grape::Entity
        expose :barcode, :name, :code, :desk, :feature, :image, :quantity, :load_at, :user_sign
      end

      class SalesmanReturnUserSign < Grape::Entity
        expose :barcode, :name, :code, :desk, :feature, :image, :quantity, :created_at, :user_sign
      end
      class LogStatus < Grape::Entity
        expose :id, :name
      end
    end
  end
end

app/controllers/api/user/users.rb
module API
  module USER
    class Users < Grape::API
      resource :users do

        get do
          present :user, current_user, with: API::USER::Entities::User
        end
        resource :device do
          desc "PATCH users/device"
          params do
            requires :device_token, type: String
          end
          patch do
            user = current_user
            user.update_attribute(:device_token, params[:device_token])

            present :updated_at, user.updated_at
          end
        end

        resource :notifications do
          desc "GET users/notifications"
          get do
            notifications = Notification.by_user(current_user.id).page(1)
            present :notifications, notifications, with: API::USER::Entities::Notification
          end
        end

        resource :notification do
          desc "POST users/notification"
          params do
            requires :title, type: String
            requires :content, type: String
            optional :token, type: String
          end
          patch do
            user = current_user
            if params[:token].present?
              user.device_token = params[:token]
            end
            ApplicationController.helpers.send_notification(user,
                                                            user.push_options('user', params[:title], params[:content]))
            present :updated_at, Time.now
          end
        end

        resource :change do
          resource :pin do
            desc "PATCH users/change/pin"
            params do
              requires :pin_code, type: String
            end
            patch do
              user = current_user
              user.pin_code = params[:pin_code]

              if user.save
                present :updated_at, user.updated_at
              else
                error!(user.errors.full_messages, 422)
              end
            end
          end
        end

      end
    end
  end
end

app/views/users/product_feature_items/_itoms_feature_item.html.erb
<% product_feature_items.each do |item| %>
  <tr class="product " id="item-<%= item.id %>" item_id="<%= item.id %>">
    <td class="va-mid"><%= item.name %></td>
    <td class="va-mid"><%= text_field_tag :barcode, item.barcode, {class: 'field'} %></td>
    <td class="va-mid"><%= number_field_tag :price, item.price, {class: 'field', min: 0, autocomplete: 'off'} %></td>
    <td class="va-mid"><%= number_field_tag :p_6_8_p, item.p_6_8_p, {class: 'field', min: 0,readonly: true, autocomplete: 'off'} %></td>
    <td class="va-mid"><%= number_field_tag :p_6_8, item.p_6_8, {class: 'field', min: 0,readonly: true, autocomplete: 'off'} %></td>
    <td class="va-mid"><%= number_field_tag :p_9_p, item.p_9_p, {class: 'field', min: 0,readonly: true, autocomplete: 'off'} %></td>
    <td class="va-mid"><%= number_field_tag :p_9_, item.p_9_, {class: 'field', min: 0,readonly: true, autocomplete: 'off'} %></td>
    <td class="va-mid"><%= number_field_tag :cost, item.cost, {class: 'field', min: 0, autocomplete: 'off'} %></td>
    <td class="va-mid"><%= number_field_tag :init_bal, item.init_bal, {class: 'field', min: 0, autocomplete: 'off'} %></td>
    <td class="va-mid"><%= number_field_tag :balance, item.balance, {class: 'field', min: 0, autocomplete: 'off'} %></td>
    <td class="va-mid"><%= text_field_tag :location_balance, item.location_balance, {class: 'field'} %></td>
    <td class="va-mid nowrap action">
      <%= image_tag '/images/loading2.gif',class: 'none' %>
      <i class="fa fa-fw fa-save none" style="font-size: 18px;color: #46a2e1" onclick="update_feature($(this), <%= item.id%>)"></i>
      <%= link_to '#', onclick: "remove_feature(#{item.id})" do %>
        <i class="fa fa-fw fa-minus-circle none" style="font-size: 15px;color: red"></i>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/users/product_feature_items/_product_location_balance_fields.html.erb
<div style="white-space: nowrap;margin-bottom: 4px">
  <%= field_errors f.object, :x %>
  <%= f.select :x, (1..22).map {|m| ["x#{m}", m]}, {prompt: 'X'}, {class: ''} %>
  <%= field_errors f.object, :y %>
  <%= f.select :y, (1..44).map {|m| ["y#{m}", m]}, {prompt: 'Y'}, {class: ''} %>
  <%= field_errors f.object, :z %>
  <%= f.select :z, (1..20).map {|m| ["z#{m}", m]}, {prompt: 'Z'}, {class: ''} %>
  <%= field_errors f.object, :quantity %>
  <%= f.number_field :quantity, {class: 'field', placeholder: t('activerecord.attributes.product_income_item.quantity'), style: 'height:auto; width: 160px'} %>
  <%= link_to_remove_association f, data: {confirm: t('are_you_sure')} do %>
    <%= nested_remove_btn %>
  <% end %>
</div>

app/views/users/product_feature_items/balance.html.erb
<% content_for :stylesheets do -%>
  <%= stylesheet_link_tag "search" %>
<% end %>
<style>
  table th,
  table td {
    font-family: Arial, sans-serif;
    font-size: 11px;
    padding: 3px 6px !important;
  }

  tr.product {
    cursor: pointer;
  }

  tr.selected,
  tr.selected:hover {
    background-color: lightyellow;
  }
</style>
<script>
    var category_max_index = 0;
</script>
<div class="content-wrapper index">
  <%= form_with url: balance_users_product_feature_items_path, method: "get", class: 'form-horizontal', local: true do |f| %>
    <div class="col-md-12 m-t-10 m-b-5">
      <div class="col-md-1 search">
        <%= text_field_tag :code, @code, {class: 'form-control search', placeholder: t('activerecord.attributes.product.code')} %>
      </div>
      <div class="col-md-2 search">
        <%= text_field_tag :name, @name, {class: 'form-control search', placeholder: t('activerecord.attributes.product.name')} %>
      </div>
      <div class="col-md-3 search">
        <%= f.select :customer_id, Customer.order_by_name.collect {|c| [c.name, c.id]}.insert(0, [t('activerecord.attributes.product.is_own'), 0]),
                     {:prompt => t('activerecord.attributes.product.customer_id'), :selected => @customer_id}, {class: 'form-control selectpicker', "data-live-search": "true"} %>
      </div>
      <div class="col-md-3 search va-mid">
        <%= select_tag :balance, options_for_select([["Үлдэгдэл", ""], ["Үлдэгдэлтэй", true], ["Үлдэгдэлгүй", false]], @balance), class: 'form-control-1' %>
        <%= select_tag :barcode, options_for_select([["Баркод", ""], ["Баркодтой", true], ["Баркодгүй", false]], @barcode), class: 'form-control-1' %>
        <%= select_tag :desk, options_for_select([["Тавиур", ""], ["Тавиуртай", true], ["Тавиургүй", false]], @desk), class: 'form-control-1' %>
      </div>
      <div class="col-md-3 search">
        <%= f.collection_select :storeroom_id, Storeroom.order_code, :id, :full_name,
                                {:selected => @storeroom_id, :include_blank => 'Бүгд'}, {class: 'form-control selectpicker', "data-live-search": true} %>

      </div>
    </div>
    <div class="col-md-12 m-b-10">
      <div class="col-md-3 search" id="product_category">
        <%= hidden_field_tag :category_id, @category_id %>
        <%= f.collection_select :main_category_id, ProductCategory.top_level, :id, :name,
                                {:prompt => t('activerecord.attributes.product.category_id'), selected: @headers.present? ? @headers.first.id : ""},
                                {class: 'form-control selectpicker', id: "category-0", ind: 0, onchange: 'callChildren(this)', "data-live-search": "true"} %>
        <% @headers.present? && @headers.each_with_index do |h, i| %>
          <% if h != @headers.first %>
            <div class="col-sm-12 sub_category" id="category-<%= i %>" style="padding: 10px 0 0 0;">
              <select class='form-control selectpicker' onchange='callChildren(this)' ind=<%= i %>>
                <% h.parent.children.each {|child| %>
                  <option value="<%= child.id %>" <%= h.id == child.id ? 'selected' : '' %>><%= child.name %></option>
                <% } %>
              </select>
            </div>
            <script type="text/javascript" charset="utf-8">
                category_max_index = <%= i + 1  %>;
            </script>
          <% end %>
        <% end %>

        <% if @product_category.present? && @product_category.children.present? %>
          <div class="col-sm-12 sub_category" id="category-<%= @headers.size %>" style="padding: 10px 0 0 0;">
            <select class='form-control selectpicker' onchange='callChildren(this)' ind=<%= @headers.size %>>
              <option value=''>Дэд ангилал сонгох</option>
              <% @product_category.children.each {|child| %>
                <option value="<%= child.id %>"><%= child.name %></option>
              <% } %>
            </select>
          </div>
        <% end %>
      </div>
      <div class="col-md-3 search m-t-5">
        <% if can? :create, Product %>
          <%= link_to 'Харилцагч', new_users_customer_import_path, class: 'btn-sm btn-warning' %>
          <%= link_to 'Үлдэгдэл нэмэх', set_balance_users_product_feature_items_path, class: 'btn-sm btn-warning', id: 'set_balance' %>
        <% end %>
      </div>
      <div class="col-md-6 search text-right">
        <%= submit_tag "#{t('controls.button.searching')} (#{@product_count})", :class => 'btn-sm blck-btn pull-right' %>
      </div>
    </div>
  <% end %>
  <section class="content container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="box" style="margin-bottom: 8px">
          <div class="box-body table-responsive no-padding">
            <%= render 'layouts/flash_message' %>
            <table class="table table-hover table-bordered">
              <tr>
                <th><%= t('activerecord.attributes.product.code') %></th>
                <th><%= t('activerecord.attributes.product.name') %></th>
                <th><%= t('activerecord.attributes.product.p_type') %></th>
                <th><%= t('activerecord.attributes.product.price') %></th>
                <th><%= t('activerecord.attributes.product.balance') %></th>
                <th><%= t('activerecord.attributes.product.category') %></th>
                <th><%= t('activerecord.attributes.product.customer_id') %></th>
              </tr>
              <% @products.each do |p| %>
                <tr class="product" id="<%= p.id %>">
                  <td class="va-mid"><%= p.code %></td>
                  <td class="va-mid"><%= p.name %></td>
                  <td class="va-mid"><%= p.p_type_i18n %></td>
                  <td class="va-mid"><%= get_currency_mn(p.price) %></td>
                  <td class="va-mid"><%= if @storeroom_id.present?
                                           @storeroom_id.to_i == 1 ? p.balance : p.store_room_balance(@storeroom_id)
                                         else
                                           p.total_balance
                                         end %></td>
                  <td class="va-mid"><%= get_name_recursive(p.category) %></td>
                  <td class="va-mid"><%= p.customer.present? ? p.customer.name : '' %></td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
        <div class="box" style="margin-bottom: 0">
          <div class="p-l-10">Барааны дэлгэрэнгүй /Сонгосон барааны сериалаар/</div>
          <div class="box-body table-responsive no-padding" id="feature_body">
          </div>
        </div>
      </div>
    </div>
    <%= paginate @products, total_pages: @total_pages %>
  </section>
</div>
<%= render 'shared/select_category_js' %>
<script>
    var tr_select_id = "";
    $(function () {
        $('tr.product').on('click', function () {
            $('tr.selected').removeClass('selected');
            $(this).addClass('selected');
            $('#feature_body').html("<div class='text-center m-t-20 w-100'><img src='/images/loading2.gif'></div>");
            tr_select_id = $(this).attr('id');
            Rails.ajax({
                url: "<%= get_feature_items_users_product_feature_items_path %>",
                type: "POST",
                data: "product_id=" + tr_select_id + "&storeroom_id=<%= @storeroom_id %>"
            });
        });

        $('#set_balance').on('click', function () {
            let href = $(this).attr('href');
            $(this).attr('href', href + "?id=" + tr_select_id);
        });
    });
</script>

app/views/users/product_feature_items/feature_add_ajax.html.erb
<% if hide_modal %>
  load_features();
<% else %>
  $('#form_modal_body').html("<%= escape_javascript render(partial: 'product_feature_item_form') %>")
  $('#form_modal_body .selectpicker').selectpicker('refresh');
  load_image_preview("#form_modal_body");
<% end %>
$('#form_modal').modal("<%= hide_modal ? 'hide':'show' %>");

app/views/users/product_feature_items/feature_items_ajax.html.erb
<% if @product_feature_items.present? %>
  $('#feature_body').html("<%= escape_javascript render(:partial => 'product_feature_item', :locals => { :product_feature_items => @product_feature_items }) %>");
<% end %>

app/views/users/product_feature_items/itoms_ajax.html.erb
<% if @product_feature_items.present? %>
  $('#mpr_body').html("<%= escape_javascript render(:partial => 'itoms_feature_item', :locals => {:product_feature_items => @product_feature_items}) %>");
  <% if @name.present? %>
    $('#name').val("<%= @name %>");
  <% end %>
  <% if @product_id.present? %>
    product_id =  <%= @product_id %>;
    $('#link').html("<a href='https://market.mn/products/<%= @product_id %>' target='_blank'>WEB LINK</a>");
  <% end %>
  $('#mpr_body .product').on('click', function () {
  $('#mpr_body tr.selected').removeClass('selected');
  $(this).addClass('selected');
  select_mrp = $(this).attr('item_id');
  });
<% else %>
  $('#mpr_body').html("<tr><td colspan='8' class='text-center'>Үр дүн олдсонгүй!</td></tr>")
<% end %>